clone:
  default:
    image: alpine
    commands:
      - echo $DRONE_REPO_PRIVATE
      - cat /root/.netrc

pipeline:
  ssh:
    image: appleboy/drone-ssh
    environment:
      - PLUGIN_HOST=tx.18e.pub
      - PLUGIN_USERNAME=ubuntu
    secrets: [ ssh_key ]
    script:
      - cd plugins4rmmv/game
      - git checkout master
      - git pull
      - cd ..
      - git status
      - git commit -m game_update -a
      - git push
