clone:
  build:
    image: alpine
    commands:
      - echo hello

pipeline:
  ssh:
    image: appleboy/drone-ssh
    host: http://111.231.90.43/
    username: ubunru
    secrets: [ ssh_key ]
    port: 22
    script:
      - cd plugins4rmmv/game
      - git checkout master
      - git pull
      - cd ..
      - git status
      - git commit -m game_update -a
      - git push



